### ISSUE TITLE
php 5.6 confliction on centos7

### ISSUE THREAD

**Issue by Mroesger** [mhulse/vagrant-latmp#128]
Hi, love the repo.

Found one issue when updating init.sh to use 5.6 

Error: php72u-json conflicts with php-pecl-jsonc-1.3.10-2.el7.remi.5.6.x86_64
Error: php72u-common conflicts with php-common-5.6.37-1.el7.remi.x86_64

just a heads up

**Comment by mhulse** [comment]
Hi! Thanks for the repot!

I've been meaning to test the PHP version switching/installing more thoroughly.

I think this might be related: #116 

Also, just FYI, I'm working on a feature branch that has some improvements:

https://github.com/mhulse/vagrant-latmp/tree/vagrant-user-provision

One of the bigger changes is I'm defaulting to the vagrant user for most things where possible (vs. using root for everything).

As soon as I get that feature branch merged, I'll improve the PHP stuff.

Thanks so much for the feedback!
